### ISSUE TITLE
Possible errors when preprocessing the videos

### ISSUE THREAD

**Issue by HenryHZY** [llyx97/TempCompass#4]
Hi @llyx97 , thanks for your great projects.

I encounter an error when processing these videos:
> OSError: MoviePy error: failed to read the first frame of video file ../videos/1100319395.mp4. That might mean that the
 file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance
 the version in the repos is deprecated. Please update to a recent version from the website.
> OSError: MoviePy error: failed to read the first frame of video file ../videos/1056433484.mp4. That might mean that the
 file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance
 the version in the repos is deprecated. Please update to a recent version from the website.

How to fix it:
> As mentioned in: https://github.com/Zulko/moviepy/issues/1078, comment the following commands at: /path/to/site-packages/moviepy/video/io/ffmpeg_reader.py
```
def close(self):
        if self.proc:
            self.proc.terminate()
            self.proc.stdout.close()
            self.proc.stderr.close()
            self.proc.wait()
            self.proc = None
        #if hasattr(self, 'lastread'):
        #    del self.lastread 
```

Actually, I am not sure whether it will affect the results. I think it would be better if you could provide the downloading link of the full video dataset after processing as an alternative:)
> 404M    ./videos
> 275M    ./videos_before_process

**Comment by llyx97** [comment]
Thanks a lot for pointing out this issue and for the great suggestion!
The processed videos can be found in this [link](https://drive.google.com/file/d/1b0ZIeRqhrUpQYxoCN_Ym_e0UW05cckYJ/view?usp=sharing).
